version: '3.4'

services:
  redis:
    image: redis:6.0.15
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  app:
    build:
      context: "."
      target: web
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=app:create_app()
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
      - OAUTHLIB_INSECURE_TRANSPORT=1

    volumes:
      - ./tests:/tests

    command: flask run -h 0.0.0.0

  worker:
    user: nobody
    build:
      context: "."
      target: worker
    command: celery --app=app.extensions.celery worker --loglevel=info

    environment:
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - app
      - redis
